# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFilterFunctions():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filterFunctions(self):
    self.driver.get("https://www.webhallen.com/")
    self.driver.find_element(By.LINK_TEXT, "Datorer & Tillbehör").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) .popular-categories-img > .ximg > .ximg-content").click()
    self.driver.find_element(By.NAME, "price").click()
    self.driver.find_element(By.NAME, "price").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .checkbox-wrap:nth-child(2) > .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".toggle-btn:nth-child(1) > .toggle-icon:nth-child(1) > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".toggle-group > .toggle-btn:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Rattar").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .checkbox-wrap:nth-child(2) > .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field").send_keys("TH8A")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Thrustmaster TH8A Add-On Shifter")))
    self.driver.find_element(By.LINK_TEXT, "Thrustmaster TH8A Add-On Shifter").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Rattar")))
    self.driver.find_element(By.LINK_TEXT, "Rattar").click()
    self.driver.find_element(By.LINK_TEXT, "Gå till toppen av sidan").click()
    self.driver.find_element(By.LINK_TEXT, "TV, Ljud & Bild").click()
    self.driver.find_element(By.LINK_TEXT, "Studio, Instrument & DJ").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .checkbox-wrap:nth-child(2) > .checkbox").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Mackie MC-250")))
    self.driver.find_element(By.LINK_TEXT, "Mackie MC-250").click()
    self.driver.find_element(By.LINK_TEXT, "Spel").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) .popular-categories-title").click()
    self.driver.find_element(By.LINK_TEXT, "Nintendo Switch OLED Model Neon Red/Neon Blue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".variant-selector > .dropdown-label > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-list-variant-item:nth-child(1) .small").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo-link .ximg-content").click()
  
