# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC

from helper_tests import simple_assert, boolean_assert

class TestSearchAndAddToCart():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--window-size=1920,1080")
    self.driver = webdriver.Chrome(options=options)
    #chrome_options.add_experimental_option("detach", True)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search_and_add_to_cart(self):
    self.driver.get("https://www.webhallen.com/")
    
    print("")
    self.driver.find_element(By.XPATH, "//header[@id=\'main-header\']/div/div/div[2]/div/div/div/input").click()
    self.driver.find_element(By.XPATH, "//header[@id=\'main-header\']/div/div/div[2]/div/div/div/input").send_keys("Nvidia")
    self.driver.find_element(By.CSS_SELECTOR, ".search-button > img").click()
    self.driver.find_element(By.LINK_TEXT, "ASUS TUF GeForce RTX 3060 OC 12GB V2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_stretch > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Till kassan").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logo-link .ximg-content").click()
    self.driver.find_element(By.LINK_TEXT, "Webhallen Config Core - 12400F / 3060Ti").click()
    self.driver.find_element(By.LINK_TEXT, "ASUS TUF GAMING M3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_large:nth-child(3) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-btn:nth-child(1) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("Intel")
    self.driver.find_element(By.CSS_SELECTOR, ".search-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Intel Core i9-12900K")))
    self.driver.find_element(By.LINK_TEXT, "Intel Core i9-12900K").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_large:nth-child(3) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("Corsair")
    self.driver.find_element(By.CSS_SELECTOR, ".search-button > img").click()
    self.driver.find_element(By.LINK_TEXT, "Corsair Vengeance RGB PRO 16GB (2x8GB)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-btn:nth-child(4) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("Pokemon")
    self.driver.find_element(By.CSS_SELECTOR, ".search-button > img").click()
    self.driver.find_element(By.LINK_TEXT, "Gå till toppen av sidan").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .filter-box-value-text").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Pokemon Divergent Powers Tin 2022")))
    self.driver.find_element(By.LINK_TEXT, "Pokemon Divergent Powers Tin 2022").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_stretch > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mobile-cart-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item").click()
  
