# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC

from helper_tests import simple_assert, boolean_assert

class TestMemberFunctions():
  def setup_method(self, method):
    chrome_options = Options()
    chrome_options.add_argument("--window-size=1920,1080")
    self.driver = webdriver.Chrome(chrome_options=chrome_options)
    #chrome_options.add_experimental_option("detach", True)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_member_functions(self):
    self.driver.get("https://www.webhallen.com/")
    self.driver.find_element(By.LINK_TEXT, "Stellunia").click()
    self.driver.find_element(By.LINK_TEXT, "Achievements").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(25) .achievement-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
    self.driver.find_element(By.LINK_TEXT, "Min avatar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-right > .avatar-item-selector:nth-child(4) .item-type").click()
    self.driver.find_element(By.CSS_SELECTOR, ".avatar-item-showcase-box:nth-child(5) .ximg-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
    self.driver.find_element(By.LINK_TEXT, "Supply Drops").click()
    self.driver.find_element(By.LINK_TEXT, "Vänner").click()
    self.driver.find_element(By.LINK_TEXT, "Topplistor").click()
    self.driver.find_element(By.LINK_TEXT, "Gsmhacker").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-select:nth-child(1) > .dropdown-label > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(3) > .list-label").click()
    self.driver.find_element(By.LINK_TEXT, "Stellunia").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field").send_keys("testtext@€@€£$")
    self.driver.find_element(By.LINK_TEXT, "Medlemsförmåner").click()
    self.driver.find_element(By.LINK_TEXT, "Medlemserbjudanden").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-filter:nth-child(1) .checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-field").send_keys("Asus")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .checkbox-wrap:nth-child(2) > .checkbox").click()
    self.driver.find_element(By.NAME, "price").send_keys("1000")
    self.driver.find_element(By.CSS_SELECTOR, ".input-number:nth-child(3)").send_keys("2000")
    self.driver.find_element(By.LINK_TEXT, "Avmarkera alla").click()
    self.driver.find_element(By.LINK_TEXT, "Önskelistor").click()
    self.driver.find_element(By.LINK_TEXT, "Delbetalningar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".toggle-btn:nth-child(4) > .toggle-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".toggle-btn:nth-child(5) > .toggle-text").click()
    self.driver.find_element(By.LINK_TEXT, "Profilinställningar").click()
  
