# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCartFunctions():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cartFunctions(self):
    self.driver.get("https://www.webhallen.com/")
    self.driver.find_element(By.LINK_TEXT, "Datorkomponenter").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) .popular-categories-img > .ximg > .ximg-content").click()
    self.driver.find_element(By.LINK_TEXT, "Hyte Y60 Midi Tower").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_secondary > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(2) .btn-remove-item > .icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-list-row:nth-child(1) .btn-remove-item > .icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close > .icon").click()
    self.driver.find_element(By.LINK_TEXT, "Köpvillkor").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tile:nth-child(1) > a").click()
  
